input_files:
  charges_path: "data/Charges_use.csv"
  damages_path: "data/Damages_use.csv"
  endorse_path: "data/Endorse_use.csv"
  primary_person_path: "data/Primary_Person_use.csv"
  restrict_path: "data/Restrict_use.csv"
  units_path: "data/Units_use.csv"

output:
  path: "output/analysis_results.json"

questions:
  analysis1: "Number of crashes in which number of males killed are greater than 2?"
  analysis2: "How many two wheelers are booked for crashes?"
  analysis3: "Top 5 Vehicle Makes of the cars present in the crashes in which driver died and Airbags did not deploy"
  analysis4: "Number of Vehicles with driver having valid licences involved in hit and run?"
  analysis5: "State that has highest number of accidents in which females are not involved?"
  analysis6: "Top 3rd to 5th VEH_MAKE_IDs that contribute to a largest number of injuries including death"
  analysis7: "Top ethnic user group of each unique body style"
  analysis8: "Among the crashed cars, what are the Top 5 Zip Codes with highest number crashes with alcohols as the contributing factor to a crash (Use Driver Zip Code)"
  analysis9: "Count of Distinct Crash IDs where No Damaged Property was observed and Damage Level (VEH_DMAG_SCL~) is above 4 and car avails Insurance"
  analysis10: "Determine the Top 5 Vehicle Makes where drivers are charged with speeding related offences, has licensed Drivers, used top 10 used vehicle colours and has car licensed with the Top 25 states with highest number of offences (to be deduced from the data)"
